apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - infra/k8s/*
build:
  # local:
  #   push: false
  googleCloudBuild: #it is for cloud build
    projectId: effective-sonar-404705 #this is the id of project created in cloud
  artifacts:
    # - image: sachin200697/auth
    - image: us.gcr.io/effective-sonar-404705/auth #google assign image name in specific formate
      context: auth
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: 'src/**/*.ts'
            dest: .
      # If you did not see your server restart after changing the index.ts file, do the following:
      # Open the package.json file in the ‘auth’ directory
      # Find the ‘start’ script
      # Update the start script to the following:
      # ts-node-dev --poll src/index.ts
